# the goal of collecting this dataset 

- Predicting Student Adaptability Levels 

# The source of the dataset

-https://vscode.dev/profile/github/6445ba822b392e2b215b9ff62d7bc3de

In [15]:
import pandas as pd
df = pd.read_csv("students_adaptability_level_online_education.csv",sep=",")
df

,Education Level,Institution Type,Gender,Age,Device,IT Student,Location,Financial Condition,Internet Type,Network Type,Flexibility Level
0,University,Private,Male,23,Tab,No,Town,Mid,Wifi,4G,Moderate
1,University,Private,Female,23,Mobile,No,Town,Mid,Mobile Data,4G,Moderate
2,College,Public,Female,18,Mobile,No,Town,Mid,Wifi,4G,Moderate
3,School,Private,Female,11,Mobile,No,Town,Mid,Mobile Data,4G,Moderate
4,School,Private,Female,18,Mobile,No,Town,Poor,Mobile Data,3G,Low
...,...,...,...,...,...,...,...,...,...,...,...
1200,College,Private,Female,18,Mobile,No,Town,Mid,Wifi,4G,Low
1201,College,Private,Female,18,Mobile,No,Rural,Mid,Wifi,4G,Moderate
1202,School,Private,Male,11,Mobile,No,Town,Mid,Mobile Data,3G,Moderate
1203,College,Private,Female,18,Mobile,No,Rural,Mid,Wifi,4G,Low
1204,School,Private,Female,11,Mobile,No,Town,Poor,Mobile Data,3G,Moderate

In [17]:
import pandas as pd
df = pd.read_csv("students_adaptability_level_online_education.csv",sep=",")
df


print(df.head())


print(df.info())


print(df.describe())

  Education Level Institution Type  Gender  Age  Device IT Student Location  \
0      University          Private    Male   23     Tab         No     Town
1      University          Private  Female   23  Mobile         No     Town
2         College           Public  Female   18  Mobile         No     Town
3          School          Private  Female   11  Mobile         No     Town
4          School          Private  Female   18  Mobile         No     Town

  Financial Condition Internet Type Network Type Flexibility Level
0                 Mid          Wifi           4G          Moderate
1                 Mid   Mobile Data           4G          Moderate
2                 Mid          Wifi           4G          Moderate
3                 Mid   Mobile Data           4G          Moderate
4                Poor   Mobile Data           3G               Low
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Education Level      1205 non-null   object
 1   Institution Type     1205 non-null   object
 2   Gender               1205 non-null   object
 3   Age                  1205 non-null   int64
 4   Device               1205 non-null   object
 5   IT Student           1205 non-null   object
 6   Location             1205 non-null   object
 7   Financial Condition  1205 non-null   object
 8   Internet Type        1205 non-null   object
 9   Network Type         1205 non-null   object
 10  Flexibility Level    1205 non-null   object
dtypes: int64(1), object(10)
memory usage: 103.7+ KB
None
               Age
count  1205.000000
mean     17.065560
std       5.830369
min       9.000000
25%      11.000000
50%      18.000000
75%      23.000000
max      27.000000